import DataBaseEntityType from "./_DataBaseEntity";

const entity: DataBaseEntityType = {
  entityName: "Customer",
  entityNameHumanized: "Customer",
  entityNameHumanizedPlural: "Customers",
  frontPath: "customers",
  fields: [
    { fieldName: "commercialName", fieldType: "String" },
    { fieldName: "corporateName", fieldType: "String" },
    {
      fieldName: "personType",
      fieldType: "Enum",
      fieldValues: "FISICA,JURIDICA",
    },
    { fieldName: "cnpj", fieldType: "String" },
    { fieldName: "cpf", fieldType: "String" },
    { fieldName: "address", fieldType: "String" },
    { fieldName: "telephone", fieldType: "String" },
    { fieldName: "email", fieldType: "String" },
    { fieldName: "technicalManagerName", fieldType: "String" },
    { fieldName: "technicalManagerSector", fieldType: "String" },
    { fieldName: "technicalManagerFunction", fieldType: "String" },
    { fieldName: "technicalManagerContact", fieldType: "String" },
    { fieldName: "technicalManagerEmail", fieldType: "String" },
  ],
  relationships: [],
  showClientView: true,
  allViewInOne: true,
  views: {
    tableLayout: {
      commercialName: { label: "Nome comercial" },
      corporateName: { label: "Razão social" },
      cnpj: { label: "CNPJ" },
      cpf: { label: "CPF" },
      telephone: { label: "Telefone" },
      email: { label: "E-mail" },
    },
    filterLayout: {
      commercialName: { label: "Nome comercial", size: 3 },
      corporateName: { label: "Razão social", size: 3  },
      cnpj: { label: "CNPJ", size: 3  },
      cpf: { label: "CPF", size: 3 },
      telephone: { label: "Telefone", size: 3  },
      email: { label: "E-mail", size: 3  },
    },
    formLayout: {
      commercialName: { label: "Nome comercial", size: 3 },
      corporateName: { label: "Razão social", size: 3  },
      cnpj: { label: "CNPJ", size: 3  },
      cpf: { label: "CPF", size: 3 },
      telephone: { label: "Telefone", size: 3  },
      email: { label: "E-mail", size: 3  },
      address: { label: "Endereço", size: 3  },
      technicalManagerName: { label: "Responsável técnico (Nome)", size: 3  },
      technicalManagerSector: { label: "Responsável técnico (Setor)", size: 3  },
      technicalManagerFunction: { label: "Responsável técnico (Função)", size: 3  },
      technicalManagerContact: { label: "Responsável técnico (Contato)", size: 3  },
      technicalManagerEmail: { label: "Responsável técnico (E-mail)", size: 3  },
    },
    viewLayout: {
      commercialName: { label: "Nome comercial", size: 3 },
      corporateName: { label: "Razão social", size: 3  },
      cnpj: { label: "CNPJ", size: 3  },
      cpf: { label: "CPF", size: 3 },
      telephone: { label: "Telefone", size: 3  },
      email: { label: "E-mail", size: 3  },
      address: { label: "Endereço", size: 3  },
      technicalManagerName: { label: "Responsável técnico (Nome)", size: 3  },
      technicalManagerSector: { label: "Responsável técnico (Setor)", size: 3  },
      technicalManagerFunction: { label: "Responsável técnico (Função)", size: 3  },
      technicalManagerContact: { label: "Responsável técnico (Contato)", size: 3  },
      technicalManagerEmail: { label: "Responsável técnico (E-mail)", size: 3  },
    },
  },
};

export default entity;
