// const BD_NAME = process.env.NODE_SERVER_BD_NAME;
// const BD_SCHEMA = process.env.NODE_SERVER_BD_SCHEMA;

const tablesName = {
  AdminAuditEntity: `AdminAuditEntity`,
  AdminAuthority: `AdminAuthority`,
  AdminPermissionProfile: `AdminPermissionProfile`,
  AdminPermissionUser: `AdminPermissionUser`,
  AdminPermission: `AdminPermission`,
  AdminProfile: `AdminProfile`,
  AdminUser: `AdminUser`,
  AdminWhiteLabel: `AdminWhiteLabel`,
  CerneDegree: `CerneDegree`,
  CerneSchool: `CerneSchool`,
  CerneClass: `CerneClass`,
  Jorney: `Jorney`,
  Theme: `Theme`,
  JorneyDegree: `JorneyDegree`,
  JorneyGalery: `JorneyGalery`,
  JorneyGalerySection: `JorneyGalerySection`,
  Essay: `Essay`,
  EssayResult: `EssayResult`,
  Reviewer: `Reviewer`,
  ConfigureCorrection: `ConfigureCorrection`,
  ConfigureCorrectionReviewer: `ConfigureCorrectionReviewer`,
  Matrix: `Matrix`,
  MatrixAnnulmentReason: `MatrixAnnulmentReason`,
  Skill: `Skill`,
  SkillItem: `SkillItem`,
  ConfigureApplication: `ConfigureApplication`,
  JorneyGalerySectionSubject: `JorneyGalerySectionSubject`,
  EssayResultComment: `EssayResultComment`,
  StudentExam: `StudentExam`,
  Exam: `Exam`,
  StudentQuestion: `StudentQuestion`,
  AreaCompetence: `AreaCompetence`,
  Competence: `Competence`,
  CompetenceGroup: `CompetenceGroup`,
  CompetenceSkill: `CompetenceSkill`,
  Contents: `Contents`,
  Discipline: `Discipline`,
  Period: `Period`,
  Questions: `Questions`,
  ExamType: `ExamType`,
  Font: `Font`,
  ExamConfigureApplication: `ExamConfigureApplication`,
  ExamCard: `ExamCard`,
  ExamCardRead: `ExamCardRead`,
  ExamTemplate: `ExamTemplate`,
  Master: `Master`,
  ExamsMaster: `ExamsMaster`,
  MasterTeacher: `MasterTeacher`,
  KnowledgeArea: `KnowledgeArea`,
  ExamsMasterKnowledgeArea: `ExamsMasterKnowledgeArea`,
  ContentsMasterTeacher: `ContentsMasterTeacher`,
  SubContents: `SubContents`,
  CernePlataform: `CernePlataform`,
  CernePlataformUser: `CernePlataformUser`,
  OLDCerneSchool: `OLDCerneSchool`,
  ThemePdf: `ThemePdf`,
  ReportByQuery: `ReportByQuery`,
  QuestionImportTemplate: 'QuestionImportTemplate',
  QuestionMatrix: 'Questoes.dbo.Matrix',
  QuestionType: 'Questoes.dbo.QuestionType',
  Question: 'Questoes.dbo.Questions',
  QuestionAlternative: 'Questoes.dbo.Alternatives',
  QuestionLevel1: 'Questoes.dbo.Level1',
  QuestionLevel2: 'Questoes.dbo.Level2',
  QuestionLevel3: 'Questoes.dbo.Level3',
  QuestionLevel4: 'Questoes.dbo.Level4',
  QuestionText: 'Questoes.dbo.Questions_Text',
  QuestionLevels: 'Questoes.dbo.Question_Levels',
  DisciplineSuperPro: 'Questoes.dbo.DisciplineSuperPro',
};

export default tablesName;
